import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { SessionProvider } from "next-auth/react"
import { FC, PropsWithChildren } from "react"

import { Layout } from "@/components/layout"
import { AntdContainer } from "@/utils/AntdContainer"
import { TRPCProvider } from "@/utils/TRPCProvider"

const inter = Inter({ subsets: ["latin"] })

const title = "App title"

export const metadata: Metadata = {
  title,
  description: "Generated by create next app",
}

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
    <body className={inter.className} style={{ margin: 0 }}>
      <SessionProvider>
        <TRPCProvider>
          <AntdContainer>
            <Layout title={title}>
              {children}
            </Layout>
          </AntdContainer>
        </TRPCProvider>
      </SessionProvider>
    </body>
    </html>
  )
}

export default RootLayout
